name: Create NuGet and GitHub Release

on:
  workflow_call:
    inputs:
      dotnet-version:
        default: '8.0.x'
        type: string
      project-paths:
        required: true
        type: string
      working-directory:
        default: './'
        type: string
      tag-prefix:
        default: ''
        type: string
    secrets:
      github-token:
        required: true
      nuget-token:
        required: true

jobs:
  release:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.pull_request.merged && startsWith(github.event.pull_request.head.ref, 'release/'))
    runs-on: ubuntu-latest
    environment: release

    steps:
      # Checkout the code
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      # Get the version from the branch name
      - id: get_version
        uses: ./.github/actions/get-version
        with:
          working-directory: ${{ inputs.working-directory }}

      # Get the prerelease flag from the branch name
      - id: get_prerelease
        uses: ./.github/actions/get-prerelease
        with:
          version: ${{ steps.get_version.outputs.version }}

      # Get the release notes
      - id: get_release_notes
        uses: ./.github/actions/get-release-notes
        with:
          token: ${{ secrets.github-token }}
          version: ${{ inputs.tag-prefix }}${{ steps.get_version.outputs.version }}
          repo_owner: ${{ github.repository_owner }}
          repo_name: ${{ github.event.repository.name }}

      # Check if the tag already exists
      - id: tag_exists
        uses: ./.github/actions/tag-exists
        with:
          tag: ${{ inputs.tag-prefix }}${{ steps.get_version.outputs.version }}
          token: ${{ secrets.github-token }}

      # Publish the release to our package manager
      - uses: ./.github/actions/nuget-publish
        if: steps.tag_exists.outputs.exists == 'false'
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
          project-paths: ${{ inputs.project-paths }}
          version: ${{ steps.get_version.outputs.version }}
          nuget-token: ${{ secrets.nuget-token }}
          nuget-directory: ${{ github.workspace}}/nuget

      # Create a release for the tag
      - uses: ./.github/actions/release-create
        if: steps.tag_exists.outputs.exists == 'false'
        with:
          token: ${{ secrets.github-token }}
          name: ${{ inputs.tag-prefix }}${{ steps.get_version.outputs.version }}
          body: ${{ steps.get_release_notes.outputs.release-notes }}
          tag: ${{ inputs.tag-prefix }}${{ steps.get_version.outputs.version }}
          commit: ${{ github.sha }}
          prerelease: ${{ steps.get_prerelease.outputs.prerelease }}
